### ISSUE TITLE
IMAGE

### ISSUE THREAD

**Issue by nopnop2002** [nopnop2002/esp8266_mqtt_uart_bridge#4]
![UART_BOOT_MESSAGE](https://user-images.githubusercontent.com/6020549/74654209-28084e80-51cd-11ea-8af5-d0c03551a484.jpg)

**Comment by zsohu** [comment]
Hi!

I've tried to use this small circuit to prevent sending the boot message, it's works for that, however the "normal" serial communication is often containing garbage characters. I tired it with 9600 and 115200 Baud. Do you have a suggestion how this can be improved to mitigate this issue? Thanks!
